### ISSUE TITLE
not enough swag + too many hax

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OSapp#1]
this repo is basickly empty and it haz 16 watchers??? u atuomatically made evrybody watch it/??/???1/?! too many hax

**Comment by Arinerron** [comment]
I'm sorry liam4 :stuck_out_tongue_winking_eye:

**Comment by TropicSapling** [comment]
@GrannyCookies so this counts as a bug? xD

**Comment by towerofnix** [comment]
It's a bug that so far seems to be abandoned :(
